shared:
    image: node:12

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - step1:  |
                labelVersion = VERSION_1.0.11.1111111111
                meta set label ${labelVersion}
            - step2:  sleep 5 && echo ok

    long:
        requires: main
        steps:
            - step1:  sleep 100 && echo ok
            - step2:  sleep 200 && echo ok